### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by ArjixWasTaken** [alashow/datmusic-android#21]
In the search page, whenever I search for anything it reloads the search page a lot of times at short intervals and has a popup saying unknown error.

PS: I manually built from source code using my own keystore and I removed the playstore credentials.

From what I see nothing that I did could have broken it except [this](https://github.com/ArjixWasTaken/datmusic-android/commit/2efbe33444dafc70a8cf7d7982eac931c7cd2a2e).

PS.2: I did use github to build the apk and all, but I made sure to delete the release as soon as I downloaded it, and I plan to do that for future builds as well.

**Comment by ArjixWasTaken** [comment]
And it is weird, since the songs it shows in the search page (before I touch the search bar) are playable and also downloadable.

**Comment by alashow** [comment]
There's a bug in demo api that's causing the error, I will fix it when I get time. It should work fine with proper api deployment.
