### ISSUE TITLE
Ability to download Albums

### ISSUE THREAD

**Issue by c4Entertainment** [alashow/datmusic-android#26]
Being able to download a whole album is a feature that would really come in handy

**Comment by alashow** [comment]
Already possible: play audio from album, save album queue as playlist, download playlist. Will add separate album downloading feature when I work on premium features.

**Comment by c4Entertainment** [comment]
Amazing. You and your team are a geniuses.

**Comment by alashow** [comment]
Thanks but I ain't got a team😂
