### ISSUE TITLE
Search not working in apk built from source code

### ISSUE THREAD

**Issue by JS9512** [alashow/datmusic-android#27]
I tried to build the apk directly from source code of both branches "master" and "private" using the following command in Android Studio:

./gradlew assembleRelease

I then uninstalled the paid apk (bundle) I've got from Play Store and installed the newly generated one to test it.

What I could see is the search function not working, every time I write some song or artist in the search box, the page stays the same, without showing anything of the searched song or of other key words.

No problem with the apk built from "private" branch, working normally (also the search function is fine) due to the fact I bought the app from Google Play (even if source code it's 2.3.0 beta 3 version, while Play Store version is 2.3.0 beta 4). On another device I've got, not connected to my Google account, the apk built from "private" branch asks me to go to Google Play Store.

Please point me to the right direction to correct the search bug of the apk built from the "master" branch, if this is a result of a mistake of mine, or update the source code to correct this if it's not.

Thanks for the great app anyway, you more than deserve the support from the paid version.

**Comment by alashow** [comment]
Play store build uses private api deployment of https://github.com/alashow/datmusic-api
