### ISSUE TITLE
Can't find license

### ISSUE THREAD

**Issue by wakaztahir** [alashow/datmusic-android#28]
what is the license of this repository

**Comment by ApokalmiX** [comment]
When a repository does not specify a license, the Apache 2 license applies by default.

**Comment by wakaztahir** [comment]
How's that, I never read that, is it some sort of convention or something...? 🤔

**Comment by alashow** [comment]
> When a repository does not specify a license, the Apache 2 license applies by default.

Lol that's not true. See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

Also, check project license at, which is applied to all source code
https://github.com/alashow/datmusic-android/blob/master/spotless/copyright.kt

I don't know the future of the project so I didn't choose good OSS license. Feel free take parts of code. Just avoid publishing in play store the whole app as is..
